### ISSUE TITLE
knative failure

### ISSUE THREAD

**Issue by jstrachan** [ndeloof/jenkinsfile-runner#1]
applying this yaml file via `kubectl apply -f build-hello.yaml` 

```yaml
apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: jbhello
spec:
  serviceAccountName: jenkins
  source:
    git:
      url: https://github.com/jstrachan/hello-world-jenkinsfile.git
      revision: master
  steps:
  - name: release
    image: jenkins/jenkinsfile-runner:latest
    imagePullPolicy: Always
```

we get the following error
```
$ kubectl logs -f jbhello-brpjf  -c build-step-release
Downloading latestCore ...
Running Pipeline on jenkins 2.121.2
Downloading Jenkins 2.121.2 ...
  19204096 (26 %)
  59753088 (80 %)

Something went wrong running your Jenkinsfile.
If you think this is a bug, please report on https://github.com/ndeloof/jenkinsfile-runner/issues
and if you miss some feature, please join https://gitter.im/jenkinsci/jenkinsfile-runner to discuss about it.
Failed to install plugins: Failed to open plugins.txt: open plugins.txt: no such file or directory
```

**Comment by ndeloof** [comment]
I can reproduce this issue, with some extra output  :
`Failed to install plugins: Failed to open plugins.txt: open plugins.txt: no such file or directory`
fixed by da2c009b

unrelated: I recommend to configure a cache for jenkinsfile-runner downloads:
```yaml
    volumeMounts:
    - name: jenkinsfile-runner-cache
      mountPath: /var/jenkinsfile-runner-cache

  volumes:
  - name: jenkinsfile-runner-cache
    hostPath:
      path: /var/jenkinsfile-runner-cache
      type: DirectoryOrCreate
```
